services:
  backend:
    container_name: resto-backend-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: resto-roulette-api:dev
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      MAIL_TOKEN: "${MAIL_TOKEN}"
    volumes:
      - ./src:/app/src
      - ./build.gradle:/app/build.gradle
      - ./settings.gradle:/app/settings.gradle
      - ./gradle:/app/gradle
    command: ["./gradlew", "bootRun", "--no-daemon"]

  db:
    container_name: resto-mysql-dev
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "resto_roulette_db"
    volumes:
      - mysql-data-dev:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql-data-dev: