FROM eclipse-temurin:21-jdk AS dev

WORKDIR /app

COPY gradlew build.gradle settings.gradle ./
COPY gradle ./gradle

RUN chmod +x gradlew

RUN ./gradlew dependencies --no-daemon || return 0

COPY src ./src

ENV SPRING_PROFILES_ACTIVE=dev

EXPOSE 8080

CMD ["./gradlew", "bootRun", "--no-daemon"]
