FROM eclipse-temurin:21-jre AS runtime

WORKDIR /app

ARG JAR_FILE=build/libs/*jar

COPY ${JAR_FILE} app.jar

ENV SPRING_PROFILES_ACTIVE=prod

EXPOSE 8080

RUN useradd -u 1000 appuser
USER appuser

CMD ["java", "-jar", "app.jar"]