[db]
resto-db ansible_host=142.93.96.246 ansible_user=root ansible_ssh_private_key_file=~/.ssh/id_ed25519

[app]
resto-backend ansible_host=142.93.96.246 ansible_user=root ansible_ssh_private_key_file=~/.ssh/id_ed25519