[db]
resto-db ansible_host=192.168.226.134 ansible_user=andydck ansible_ssh_private_key_file=~/.ssh/id_ed25519

[app]
resto-backend ansible_host=192.168.226.130 ansible_user=andydck ansible_ssh_private_key_file=~/.ssh/id_ed25519