spring:
  application:
    name: resto-roulette-api
  datasource:
    username: 'root'
    url:
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          google:
            authorization-uri:
            token-uri:
            user-info-uri:
            user-name-attribute: sub
logging:
  level:
    org:
      springframework:
        security: ERROR
security:
  jwt:
    expiration-time: ''
    secret-key:
springdoc:
  swagger-ui:
    path: "/swagger-ui.html"
mail:
  token: ""
  verification_url: TODO
server:
  ssl:
    key-store-password: ""
    key-store-type: ""
    enabled: ""
    key-store: "/etc/ssl/springboot/keystore.p12"
  port: "443"

