spring:
  application:
    name: resto-roulette-api
  datasource:
    username: 'root'
    url: jdbc:mysql://localhost:3306/resto_roulette
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
logging:
  level:
    org:
      springframework:
        security: INFO
security:
  jwt:
    expiration-time: '3600000'
    secret-key: 3e9f79e94251ca53bc05f255779c84e9dbecca634b028569f966f619ef4563b3