- name: Deploy Spring Boot backend via Docker
  hosts: app
  become: no
  vars:
    app_dir: "/home/arthur/npm/spring_app"
    local_repo: "/home/arthur-pascal/Documents/Epitech/Resto-roulette/resto-roulette-api"
  vars_files:
    - ../group_vars/app/vault.yml

  tasks:
    - name: Build Spring Boot JAR locally
      delegate_to: localhost
      shell: |
        cd "{{ local_repo }}"
        ./gradlew clean bootJar
      args:
        executable: /bin/bash

    - name: Extract Doppler secrets to local .env file
      delegate_to: localhost
      shell: |
          doppler secrets download --format docker --no-file --project "{{ doppler_project }}" --config "{{ doppler_config }}" --token "{{ doppler_service_token }}" > /tmp/.env
      args:
        executable: /bin/bash

    - name: Ensure destination directory exists on server
      file:
        path: "{{ app_dir }}"
        state: directory
        mode: "0755"

    - name: Upload Spring Boot JAR to server
      copy:
        src: "{{ local_repo }}/build/libs/resto-0.0.1-SNAPSHOT.jar"
        dest: "{{ app_dir }}/app.jar"
        mode: "0644"

    - name: Upload .env file to server
      copy:
        src: "/tmp/.env"
        dest: "{{ app_dir }}/.env"
        mode: "0600"

    - name: Restart Spring Boot container
      shell: |
        cd /home/arthur/npm
        docker compose up -d --force-recreate spring-app